name: day_pilot
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  hooks_riverpod: ^2.3.7
  flutter_hooks: ^0.20.0
  flutter_screenutil: ^5.8.4
  intl: ^0.18.0
  fvm: ^2.4.1
  lottie: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_launcher_icons: ^0.11.0
  # flutter_native_splash: ^2.2.19
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svgs/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
