name: day_pilot
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  hooks_riverpod: ^2.3.7
  flutter_hooks: ^0.20.0
  flutter_screenutil: ^5.8.4
  intl: ^0.18.0
  fvm: ^2.4.1
  lottie: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_launcher_icons: ^0.11.0
  # flutter_native_splash: ^2.2.19
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/static/Poppins-Regular.ttf
        - asset: assets/fonts/static/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/static/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/static/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/static/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/Poppins-Thin.ttf
          weight: 100
